name: Build and Push Java 22 Yolk

on:



  push:
    branches: [ main ]



jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2



        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/pro-nil/java22-yolk:latest
